### ISSUE TITLE
Using deequ with java 11

### ISSUE THREAD

**Issue by sbaltus** [awslabs/deequ#123]
Hi there, 

I'm evaluating `deequ` using `java 11`, and I keep failing to execute a simple `ColumnProfilerRunner` or a `VerificationSuite` using a very small file. I might be doing something wrong. 
Here is an example of my code : 
```
Dataset<Row> logData = spark.read().json(logFile); 
ColumnProfiles cpr = new ColumnProfilerRunner().onData(logData).run();
```
When executing this I have the following exception: 
```
Exception in thread "main" com.amazon.deequ.analyzers.runners.MetricCalculationRuntimeException: org.apache.spark.sql.catalyst.errors.package$TreeNodeException: execute, tree:
HashAggregate(keys=[], functions=[sum(cast(cast(isnotnull(app_id#8) as int) as bigint)), count(1), stateful_approx_count_distinct(app_id#8, 0, 0), statefuldatatype(app_id#8, org.apache.spark.sql.StatefulDataType@a4388f1, 0, 0), sum(cast(cast(isnotnull(event_name#9) as int) as bigint)), count(1), stateful_approx_count_distinct(event_name#9, 0, 0), statefuldatatype(event_name#9, org.apache.spark.sql.StatefulDataType@3687b83c, 0, 0), sum(cast(cast(isnotnull(event_type#10) as int) as bigint)), count(1), stateful_approx_count_distinct(event_type#10, 0, 0), statefuldatatype(event_type#10, org.apache.spark.sql.StatefulDataType@4cbd17b3, 0, 0), sum(cast(cast(isnotnull(index#11) as int) as bigint)), count(1), stateful_approx_count_distinct(index#11, 0, 0), statefuldatatype(index#11, org.apache.spark.sql.StatefulDataType@3a5c6009, 0, 0), sum(cast(cast(isnotnull(object_ids#12) as int) as bigint)), count(1), stateful_approx_count_distinct(object_ids#12, 0, 0), sum(cast(cast(isnotnull(positions#13) as int) as bigint)), count(1), stateful_approx_count_distinct(positions#13, 0, 0), sum(cast(cast(isnotnull(query_id#14) as int) as bigint)), count(1), ... 14 more fields], output=[sum(CAST((app_id IS NOT NULL) AS INT))#2380L, count(1)#2381L, stateful_approx_count_distinct(app_id)#2486, statefuldatatype(app_id)#2497, sum(CAST((event_name IS NOT NULL) AS INT))#2498L, count(1)#2499L, stateful_approx_count_distinct(event_name)#2604, statefuldatatype(event_name)#2615, sum(CAST((event_type IS NOT NULL) AS INT))#2616L, count(1)#2617L, stateful_approx_count_distinct(event_type)#2722, statefuldatatype(event_type)#2733, sum(CAST((index IS NOT NULL) AS INT))#2734L, count(1)#2735L, stateful_approx_count_distinct(index)#2840, statefuldatatype(index)#2851, sum(CAST((object_ids IS NOT NULL) AS INT))#2852L, count(1)#2853L, stateful_approx_count_distinct(object_ids)#2958, sum(CAST((positions IS NOT NULL) AS INT))#2959L, count(1)#2960L, stateful_approx_count_distinct(positions)#3065, sum(CAST((query_id IS NOT NULL) AS INT))#3066L, count(1)#3067L, ... 14 more fields])
+- Exchange SinglePartition
   +- HashAggregate(keys=[], functions=[partial_sum(cast(cast(isnotnull(app_id#8) as int) as bigint)), partial_count(1), partial_stateful_approx_count_distinct(app_id#8, 0, 0), partial_statefuldatatype(app_id#8, org.apache.spark.sql.StatefulDataType@a4388f1, 0, 0), partial_sum(cast(cast(isnotnull(event_name#9) as int) as bigint)), partial_count(1), partial_stateful_approx_count_distinct(event_name#9, 0, 0), partial_statefuldatatype(event_name#9, org.apache.spark.sql.StatefulDataType@3687b83c, 0, 0), partial_sum(cast(cast(isnotnull(event_type#10) as int) as bigint)), partial_count(1), partial_stateful_approx_count_distinct(event_type#10, 0, 0), partial_statefuldatatype(event_type#10, org.apache.spark.sql.StatefulDataType@4cbd17b3, 0, 0), partial_sum(cast(cast(isnotnull(index#11) as int) as bigint)), partial_count(1), partial_stateful_approx_count_distinct(index#11, 0, 0), partial_statefuldatatype(index#11, org.apache.spark.sql.StatefulDataType@3a5c6009, 0, 0), partial_sum(cast(cast(isnotnull(object_ids#12) as int) as bigint)), partial_count(1), partial_stateful_approx_count_distinct(object_ids#12, 0, 0), partial_sum(cast(cast(isnotnull(positions#13) as int) as bigint)), partial_count(1), partial_stateful_approx_count_distinct(positions#13, 0, 0), partial_sum(cast(cast(isnotnull(query_id#14) as int) as bigint)), partial_count(1), ... 14 more fields], output=[sum#4698L, count#4699L, MS[0]#3580L, MS[1]#3581L, MS[2]#3582L, MS[3]#3583L, MS[4]#3584L, MS[5]#3585L, MS[6]#3586L, MS[7]#3587L, MS[8]#3588L, MS[9]#3589L, MS[10]#3590L, MS[11]#3591L, MS[12]#3592L, MS[13]#3593L, MS[14]#3594L, MS[15]#3595L, MS[16]#3596L, MS[17]#3597L, MS[18]#3598L, MS[19]#3599L, MS[20]#3600L, MS[21]#3601L, ... 552 more fields])
      +- *FileScan json [app_id#8,event_name#9,event_type#10,index#11,object_ids#12,positions#13,query_id#14,timestamp#15,user_token#16,version#17L] Batched: false, Format: JSON, Location: InMemoryFileIndex[file:/Users/.../1553688656310357341.json], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<app_id:string,event_name:string,event_type:string,index:string,object_ids:array<string>,po...

	at com.amazon.deequ.analyzers.runners.MetricCalculationException$.wrapIfNecessary(MetricCalculationException.scala:74)
	at com.amazon.deequ.analyzers.Analyzers$.metricFromFailure(Analyzer.scala:441)
	at com.amazon.deequ.analyzers.StandardScanShareableAnalyzer.toFailureMetric(Analyzer.scala:206)
	at com.amazon.deequ.analyzers.StandardScanShareableAnalyzer.toFailureMetric(Analyzer.scala:190)
	at com.amazon.deequ.analyzers.runners.AnalysisRunner$$anonfun$liftedTree1$1$2.apply(AnalysisRunner.scala:312)
	at com.amazon.deequ.analyzers.runners.AnalysisRunner$$anonfun$liftedTree1$1$2.apply(AnalysisRunner.scala:312)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.immutable.List.map(List.scala:285)
	at com.amazon.deequ.analyzers.runners.AnalysisRunner$.liftedTree1$1(AnalysisRunner.scala:312)
	at com.amazon.deequ.analyzers.runners.AnalysisRunner$.runScanningAnalyzers(AnalysisRunner.scala:295)
	at com.amazon.deequ.analyzers.runners.AnalysisRunner$.doAnalysisRun(AnalysisRunner.scala:154)
	at com.amazon.deequ.analyzers.runners.AnalysisRunBuilder.run(AnalysisRunBuilder.scala:101)
	at com.amazon.deequ.profiles.ColumnProfiler$.profile(ColumnProfiler.scala:124)
	at com.amazon.deequ.profiles.ColumnProfilerRunner.run(ColumnProfilerRunner.scala:57)
	at com.amazon.deequ.profiles.ColumnProfilerRunBuilder.run(ColumnProfilerRunBuilder.scala:132)
	at Main.main(Main.java:29)
Caused by: org.apache.spark.sql.catalyst.errors.package$TreeNodeException: execute, tree:
```
I've attached the full stacktrace if it can be of any help. 
[stack.txt](https://github.com/awslabs/deequ/files/3490138/stack.txt)

Am I missing something here ? 

Thanks a lot for your help, I'd love to use `deequ` sounds very useful for my use cases. 

Stephanie

**Comment by sscdotopen** [comment]
Hi Stephanie,

It seems that something is wrong with the queries that ColumnProfilerRunner is generating. Would you be able to send me the json file (or a sample of it) for debugging this? If not, could you describe the schema of the data? Does it contain nested attributes (which we dont support in deequ)?

**Comment by sbaltus** [comment]
Hi Sebastian, 

Thanks a lot for your prompt reply.
Here's the schema displayed using `printSchema` on the `dataset`: 
```
root
 |-- app_id: string (nullable = true)
 |-- event_name: string (nullable = true)
 |-- event_type: string (nullable = true)
 |-- index: string (nullable = true)
 |-- object_ids: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- positions: array (nullable = true)
 |    |-- element: long (containsNull = true)
 |-- query_id: string (nullable = true)
 |-- timestamp: string (nullable = true)
 |-- user_token: string (nullable = true)
 |-- version: long (nullable = true)
```
is `deequ` supporting arrays ? 
And here is a sample of the dataset : 
```
{"app_id":"TEST01","index":"","event_type":"example","event_name":"legacy","object_ids":["999BOL-D071061___5c98233dd2690"],"positions":[2],"query_id":"5f5a5dc55b9c6a07beb60588884cf999","user_token":"","version":0,"timestamp":"2019-03-27T12:11:02.994Z"}
{"app_id":"TEST01","index":"","event_type":"example","event_name":"legacy","object_ids":["705PRO-0418139___5c97e47158fbb"],"positions":[10],"query_id":"1b4f3a4d429b43bc2dd4638ce4ec7085","user_token":"","version":0,"timestamp":"2019-03-27T12:11:11.906Z"}
```

Thanks a lot,

**Comment by sscdotopen** [comment]
Hi Stephanie, we don't support nested data at the moment, I would suspect that this is the reason why you see the failure. Could you try to un-nest the data and  run the profiling again?

**Comment by sbaltus** [comment]
So I've tried again, using only the first column (app_id): : 
```
root
 |-- app_id: string (nullable = true)
```
but I still have an exception : 
```
INFO FileSourceScanExec: Planning scan with bin packing, max size: 4196562 bytes, open cost is considered as scanning 4194304 bytes.
Exception in thread "main" com.amazon.deequ.analyzers.runners.MetricCalculationRuntimeException: org.apache.spark.sql.catalyst.errors.package$TreeNodeException: execute, tree:
HashAggregate(keys=[], functions=[sum(cast(cast(isnotnull(app_id#8) as int) as bigint)), count(1), stateful_approx_count_distinct(app_id#8, 0, 0), statefuldatatype(app_id#8, org.apache.spark.sql.StatefulDataType@1dfd6023, 0, 0), count(1)], output=[sum(CAST((app_id IS NOT NULL) AS INT))#297L, count(1)#298L, stateful_approx_count_distinct(app_id)#403, statefuldatatype(app_id)#414, count(1)#415L])
+- Exchange SinglePartition
   +- HashAggregate(keys=[], functions=[partial_sum(cast(cast(isnotnull(app_id#8) as int) as bigint)), partial_count(1), partial_stateful_approx_count_distinct(app_id#8, 0, 0), partial_statefuldatatype(app_id#8, org.apache.spark.sql.StatefulDataType@1dfd6023, 0, 0), partial_count(1)], output=[sum#539L, count#540L, MS[0]#468L, MS[1]#469L, MS[2]#470L, MS[3]#471L, MS[4]#472L, MS[5]#473L, MS[6]#474L, MS[7]#475L, MS[8]#476L, MS[9]#477L, MS[10]#478L, MS[11]#479L, MS[12]#480L, MS[13]#481L, MS[14]#482L, MS[15]#483L, MS[16]#484L, MS[17]#485L, MS[18]#486L, MS[19]#487L, MS[20]#488L, MS[21]#489L, ... 36 more fields])
      +- *FileScan json [app_id#8] Batched: false, Format: JSON, Location: InMemoryFileIndex[file:/Users/stephaniebaltus/45/12_clicks/12/10/1553688656310357341.json], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<app_id:string>

	at com.amazon.deequ.analyzers.runners.MetricCalculationException$.wrapIfNecessary(MetricCalculationException.scala:74)
	at com.amazon.deequ.analyzers.Analyzers$.metricFromFailure(Analyzer.scala:441)
	at com.amazon.deequ.analyzers.StandardScanShareableAnalyzer.toFailureMetric(Analyzer.scala:206)
	at com.amazon.deequ.analyzers.StandardScanShareableAnalyzer.toFailureMetric(Analyzer.scala:190)
	at com.amazon.deequ.analyzers.runners.AnalysisRunner$$anonfun$liftedTree1$1$2.apply(AnalysisRunner.scala:312)
	at com.amazon.deequ.analyzers.runners.AnalysisRunner$$anonfun$liftedTree1$1$2.apply(AnalysisRunner.scala:312)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.immutable.List.map(List.scala:285)
	at com.amazon.deequ.analyzers.runners.AnalysisRunner$.liftedTree1$1(AnalysisRunner.scala:312)
	at com.amazon.deequ.analyzers.runners.AnalysisRunner$.runScanningAnalyzers(AnalysisRunner.scala:295)
	at com.amazon.deequ.analyzers.runners.AnalysisRunner$.doAnalysisRun(AnalysisRunner.scala:154)
	at com.amazon.deequ.analyzers.runners.AnalysisRunBuilder.run(AnalysisRunBuilder.scala:101)
	at com.amazon.deequ.profiles.ColumnProfiler$.profile(ColumnProfiler.scala:124)
	at com.amazon.deequ.profiles.ColumnProfilerRunner.run(ColumnProfilerRunner.scala:57)
	at com.amazon.deequ.profiles.ColumnProfilerRunBuilder.run(ColumnProfilerRunBuilder.scala:132)
	at Main.main(Main.java:40)
```

**Comment by sscdotopen** [comment]
Hmm, strange. It also seems that Spark currently does not support Java 11, as outlined here: https://stackoverflow.com/questions/51330840/why-apache-spark-does-not-work-with-java-10-we-get-illegal-reflective-then-java

Can you try to run with another java version?

**Comment by sbaltus** [comment]
Hi Sebastian, 

I tried with java 8 and it solves the issue, thanks for your help !
