### ISSUE TITLE
Scala 2.12

### ISSUE THREAD

**Issue by mkeshav** [awslabs/deequ#193]
Can this library be used with Scala 2.12?

**Comment by sscdotopen** [comment]
Hi Keshav,

We have not tried Deequ with Scala 2.12. My guess is that it would work if you update the dependencies accordingly.

**Comment by timgent** [comment]
Unfortunately it doesn't seem to work with Scala 2.12. 

I tried with Scala version 2.12.8, and just the following dependencies:
"org.apache.spark" % "spark-core_2.12" % "2.4.5"
"com.amazon.deequ" % "deequ" % "1.0.2"


Produces this error on build:
```
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/private/tmp/spark-data-quality/"), "root"):
[error]    org.apache.spark:spark-launcher _2.12, _2.11
[error]    org.json4s:json4s-ast _2.12, _2.11
[error]    org.apache.spark:spark-network-shuffle _2.12, _2.11
[error]    com.twitter:chill _2.12, _2.11
[error]    org.json4s:json4s-jackson _2.12, _2.11
[error]    com.fasterxml.jackson.module:jackson-module-scala _2.12, _2.11
[error]    org.json4s:json4s-core _2.12, _2.11
[error]    org.apache.spark:spark-unsafe _2.12, _2.11
[error]    org.apache.spark:spark-tags _2.12, _2.11
[error]    org.apache.spark:spark-core _2.12, _2.11
[error]    org.apache.spark:spark-network-common _2.12, _2.11
[error] java.lang.RuntimeException: Conflicting cross-version suffixes in: org.apache.spark:spark-launcher, org.json4s:json4s-ast, org.apache.spark:spark-network-shuffle, com.twitter:chill, org.json4s:json4s-jackson, com.fasterxml.jackson.module:jackson-module-scala, org.json4s:json4s-core, org.apache.spark:spark-unsafe, org.apache.spark:spark-tags, org.apache.spark:spark-core, org.apache.spark:spark-network-common
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbt.librarymanagement.ConflictWarning$.processCrossVersioned(ConflictWarning.scala:39)
[error] 	at sbt.librarymanagement.ConflictWarning$.apply(ConflictWarning.scala:19)
[error] 	at sbt.Classpaths$.$anonfun$ivyBaseSettings$70(Defaults.scala:2483)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (update) Conflicting cross-version suffixes in: org.apache.spark:spark-launcher, org.json4s:json4s-ast, org.apache.spark:spark-network-shuffle, com.twitter:chill, org.json4s:json4s-jackson, com.fasterxml.jackson.module:jackson-module-scala, org.json4s:json4s-core, org.apache.spark:spark-unsafe, org.apache.spark:spark-tags, org.apache.spark:spark-core, org.apache.spark:spark-network-common
[error] Total time: 10 s, completed 29-Apr-2020 23:20:37
```

If it's helpful I can push the minimal code for this to Github

**Comment by CarterKilgour** [comment]
@timgent inspired by the post [here](https://github.com/Azure/azure-cosmosdb-spark/issues/239) I was able to get around this issue with the following:

```
libraryDependencies += "org.apache.spark"  %% "spark-core"  % "3.1.0" % "provided"
libraryDependencies +=  "org.apache.spark" %% "spark-sql"   % "3.0.1" % "provided"
libraryDependencies += "com.amazon.deequ"  % "deequ"        % "1.1.0_spark-3.0-scala-2.12" % "provided" exclude("org.apache.spark", "spark-core_2.11") exclude("org.apache.spark", "spark-sql_2.11")
```

**Comment by ananthsathvick** [comment]
> @timgent inspired by the post [here](https://github.com/Azure/azure-cosmosdb-spark/issues/239) I was able to get around this issue with the following:
> 
> ```
> libraryDependencies += "org.apache.spark"  %% "spark-core"  % "3.1.0" % "provided"
> libraryDependencies +=  "org.apache.spark" %% "spark-sql"   % "3.0.1" % "provided"
> libraryDependencies += "com.amazon.deequ"  % "deequ"        % "1.1.0_spark-3.0-scala-2.12" % "provided" exclude("org.apache.spark", "spark-core_2.11") exclude("org.apache.spark", "spark-sql_2.11")
> ```

This worked for me 
Scala version 2.12.12
Spark version 3.1.1

**Comment by lange-labs** [comment]
Resolving - Scala 2.12 is supported now
