### ISSUE TITLE
Issue writing to FileSystemMetricsRepository with S3 URI

### ISSUE THREAD

**Issue by robmoore** [awslabs/deequ#292]
Greetings! Thanks for sharing this project with the world.

I'm trying to write to an empty prefix on S3 like so:

`val repository = FileSystemMetricsRepository(session, "s3://my-metrics-repo/my_prefix")`

and am seeing the following error:

```
java.io.IOException: Can not delete s3n://my-metrics-repo/my_prefix at is a not empty directory and recurse option is false
  at com.amazon.ws.emr.hadoop.fs.s3n.S3NativeFileSystem.delete(S3NativeFileSystem.java:487)
  at com.amazon.ws.emr.hadoop.fs.EmrFileSystem.delete(EmrFileSystem.java:342)
  at com.amazon.deequ.repository.fs.FileSystemMetricsRepository$.writeToFileOnDfs(FileSystemMetricsRepository.scala:192)
  at com.amazon.deequ.repository.fs.FileSystemMetricsRepository.save(FileSystemMetricsRepository.scala:54)
  at com.amazon.deequ.VerificationSuite$$anonfun$saveOrAppendResultsIfNecessary$1$$anonfun$apply$5.apply(VerificationSuite.scala:190)
  at com.amazon.deequ.VerificationSuite$$anonfun$saveOrAppendResultsIfNecessary$1$$anonfun$apply$5.apply(VerificationSuite.scala:181)
  at scala.Option.foreach(Option.scala:257)
  at com.amazon.deequ.VerificationSuite$$anonfun$saveOrAppendResultsIfNecessary$1.apply(VerificationSuite.scala:181)
  at com.amazon.deequ.VerificationSuite$$anonfun$saveOrAppendResultsIfNecessary$1.apply(VerificationSuite.scala:180)
  at scala.Option.foreach(Option.scala:257)
  at com.amazon.deequ.VerificationSuite.saveOrAppendResultsIfNecessary(VerificationSuite.scala:180)
  at com.amazon.deequ.VerificationSuite.doVerificationRun(VerificationSuite.scala:136)
  at com.amazon.deequ.VerificationRunBuilder.run(VerificationRunBuilder.scala:164)
```

I've tried just using 's3' as well as 's3n' based on another issue here that suggested it as a supported protocol.

**Comment by robmoore** [comment]
OK, got this to work. I misunderstood what the path was supposed to convey (I thought it was a path to the parent prefix rather than to the resulting file itself). I created a prefix (ala `my_prefix`) manually anticipating that's where the results would be written (I was thinking the actual filename would be auto-generated like Parquet output) and as a result this blocked Deequ from writing the results.
