### ISSUE TITLE
Add support for Spark 3.2

### ISSUE THREAD

**Issue by alexott** [awslabs/deequ#380]
As part of "[SPARK-35558] Optimizes for multi-quantile retrieval", Spark 3.2 changed the signature of `ApproximatePercentile.getPercentiles` function and this broke the Deequ:

```
NoSuchMethodError: org.apache.spark.sql.catalyst.expressions.aggregate.ApproximatePercentile$PercentileDigest.getPercentiles([D)[D
	at com.amazon.deequ.analyzers.ApproxQuantile.fromAggregationResult(ApproxQuantile.scala:84)
	at com.amazon.deequ.analyzers.ScanShareableAnalyzer.metricFromAggregationResult(Analyzer.scala:192)
	at com.amazon.deequ.analyzers.ScanShareableAnalyzer.metricFromAggregationResult$(Analyzer.scala:185)
	at com.amazon.deequ.analyzers.ApproxQuantile.metricFromAggregationResult(ApproxQuantile.scala:50)
	at com.amazon.deequ.analyzers.runners.AnalysisRunner$.successOrFailureMetricFrom(AnalysisRunner.scala:362)
	at com.amazon.deequ.analyzers.runners.AnalysisRunner$.$anonfun$runScanningAnalyzers$5(AnalysisRunner.scala:330)
```

**Comment by lange-labs** [comment]
Thanks for sharing the issue. My understanding is that Spark 3.2 is not yet released. We'll add support for Spark 3.2 when it is released.

**Comment by TammoR** [comment]
Yes. We're working on the release.

**Comment by sdandey** [comment]
> Yes. We're working on the release.

Hi TammoR, do you have a timeline on when the support can be released.  If you have a specific branch that has the support for 3.2.  Please provide the link to that

**Comment by TammoR** [comment]
Hi sdandey. We're working on it on this branch: https://github.com/awslabs/deequ/tree/tammruka/2.0.0-spark-3.2.0
We do have limited bandwidth at the moment. If you're able to contribute to this branch towards supporting Spark 3.2, you would be most welcome to.

**Comment by deenkar** [comment]
[https://github.com/awslabs/deequ/issues/399](url)

**Comment by joesan** [comment]
Is there any update on this?

**Comment by joesan** [comment]
Managed to fix few of the errors. Left with the following after updading pom.xml to Scala version 2.13 and Spark version to 3.2.

```
[INFO] --- scala-maven-plugin:4.5.6:compile (scala-compile-first) @ deequ ---
[INFO] Using incremental compilation using Mixed compile order
[INFO] Compiler bridge file: /home/joesan/.sbt/1.0/zinc/org.scala-sbt/org.scala-sbt-compiler-bridge_2.13-1.5.8-bin_2.13.0__52.0-1.5.8_20211211T222914.jar
[INFO] compiling 106 Scala sources and 1 Java source to /home/joesan/Projects/Private/scala-projects/deequ/target/classes ...
[ERROR] /home/joesan/Projects/Private/scala-projects/deequ/src/main/scala/com/amazon/deequ/analyzers/QuantileNonSample.scala:55: missing argument list for method to in trait IterableOnceOps
Unapplied methods are only converted to functions when a function type is expected.
You can make this conversion explicit by writing `to _` or `to(_)` instead of `to`.
[ERROR] /home/joesan/Projects/Private/scala-projects/deequ/src/main/scala/com/amazon/deequ/repository/AnalysisResultSerde.scala:414: overloaded method value apply with alternatives:
  (columns: Seq[String])com.amazon.deequ.analyzers.CountDistinct <and>
  (column: String)com.amazon.deequ.analyzers.CountDistinct
 cannot be applied to (scala.collection.Seq[String])
[ERROR] /home/joesan/Projects/Private/scala-projects/deequ/src/main/scala/com/amazon/deequ/repository/AnalysisResultSerde.scala:417: overloaded method value apply with alternatives:
  (columns: Seq[String],where: Option[String])com.amazon.deequ.analyzers.Distinctness <and>
  (column: String)com.amazon.deequ.analyzers.Distinctness
 cannot be applied to (scala.collection.Seq[String])
[ERROR] /home/joesan/Projects/Private/scala-projects/deequ/src/main/scala/com/amazon/deequ/repository/AnalysisResultSerde.scala:423: type mismatch;
 found   : Seq[String] (in scala.collection) 
 required: Seq[String] (in scala.collection.immutable) 
[ERROR] /home/joesan/Projects/Private/scala-projects/deequ/src/main/scala/com/amazon/deequ/repository/AnalysisResultSerde.scala:426: overloaded method value apply with alternatives:
  (columns: Seq[String],where: Option[String])com.amazon.deequ.analyzers.UniqueValueRatio <and>
  (column: String)com.amazon.deequ.analyzers.UniqueValueRatio
 cannot be applied to (scala.collection.Seq[String])
[ERROR] /home/joesan/Projects/Private/scala-projects/deequ/src/main/scala/com/amazon/deequ/repository/AnalysisResultSerde.scala:429: overloaded method value apply with alternatives:
  (columns: Seq[String],where: Option[String])com.amazon.deequ.analyzers.Uniqueness <and>
  (column: String)com.amazon.deequ.analyzers.Uniqueness
 cannot be applied to (scala.collection.Seq[String])
[ERROR] 6 errors found
```

**Comment by tanvn** [comment]
Hi @TammoR
I just created a PR for this issue 
https://github.com/awslabs/deequ/pull/416
Could you please take a look ?
It seems that I do not have the privilege of setting Reviewers and Assignees, so I would appreciate if you could take care of that part too 🙇

**Comment by lange-labs** [comment]
Hi @tanvn 
Thanks for the great work on this issue! We merged the code with master. 

A new Deequ version [2.0.1-spark-3.2](https://mvnrepository.com/artifact/com.amazon.deequ/deequ/2.0.1-spark-3.2) is now available.

**Comment by AlecVivian** [comment]
Hi @lange-labs @TammoR 
It looks like this ticket is still open, and now we're on Spark 3.3.0. is this a fluke? Are we good to add compatibility ask for 3.3.0?

**Comment by sudsali** [comment]
Closing as fixed. Spark 3.2 support was added via PR #416 and released as version 2.0.1-spark-3.2. Current releases support Spark 3.5.
