### ISSUE TITLE
NewChildrenInternal(scala.collection.IndexedSeq) --- Error with newer spark version and deequ version

### ISSUE THREAD

**Issue by aashishkITV** [awslabs/deequ#398]
Running Constraint Suggestions for Deequ with Spark 3.2 , Deequ 2.0 : 

java.lang.AbstractMethodError: Receiver class org.apache.spark.sql.catalyst.expressions.aggregate.StatefulHyperloglogPlus does not define or inherit an implementation of the resolved method 'abstract org.apache.spark.sql.catalyst.trees.TreeNode withNewChildrenInternal(scala.collection.IndexedSeq)' of abstract class org.apache.spark.sql.catalyst.trees.TreeNode.
  at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$withNewChildren$2(TreeNode.scala:359)
  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:82)
  at org.apache.spark.sql.catalyst.trees.TreeNode.withNewChildren(TreeNode.scala:358)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:595)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:486)
  at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$3(TreeNode.scala:486)
  at scala.collection.immutable.List.map(List.scala:293)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:595)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:486)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:457)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transform(TreeNode.scala:425)
  at org.apache.spark.sql.catalyst.util.package$.usePrettyExpression(package.scala:128)
  at org.apache.spark.sql.catalyst.util.package$.toPrettySQL(package.scala:158)
  at org.apache.spark.sql.RelationalGroupedDataset.alias(RelationalGroupedDataset.scala:89)
  at org.apache.spark.sql.RelationalGroupedDataset.$anonfun$toDF$1(RelationalGroupedDataset.scala:65)
  at scala.collection.immutable.List.map(List.scala:297)
  at org.apache.spark.sql.RelationalGroupedDataset.toDF(RelationalGroupedDataset.scala:65)
  at org.apache.spark.sql.RelationalGroupedDataset.agg(RelationalGroupedDataset.scala:255)
  at org.apache.spark.sql.Dataset.agg(Dataset.scala:1890)
  at com.amazon.deequ.analyzers.runners.AnalysisRunner$.liftedTree1$1(AnalysisRunner.scala:326)
  at com.amazon.deequ.analyzers.runners.AnalysisRunner$.runScanningAnalyzers(AnalysisRunner.scala:318)
  at com.amazon.deequ.analyzers.runners.AnalysisRunner$.doAnalysisRun(AnalysisRunner.scala:167)
  at com.amazon.deequ.analyzers.runners.AnalysisRunBuilder.run(AnalysisRunBuilder.scala:110)
  at com.amazon.deequ.profiles.ColumnProfiler$.profile(ColumnProfiler.scala:141)
  at com.amazon.deequ.profiles.ColumnProfilerRunner.run(ColumnProfilerRunner.scala:72)
  at com.amazon.deequ.profiles.ColumnProfilerRunBuilder.run(ColumnProfilerRunBuilder.scala:185)
  at com.amazon.deequ.suggestions.ConstraintSuggestionRunner.profileAndSuggest(ConstraintSuggestionRunner.scala:203)
  at com.amazon.deequ.suggestions.ConstraintSuggestionRunner.run(ConstraintSuggestionRunner.scala:102)
  at com.amazon.deequ.suggestions.ConstraintSuggestionRunBuilder.run(ConstraintSuggestionRunBuilder.scala:226)
  at constraintSuggestor(/Users/aashish.khetarpal/iTV/repositories/iTVRepo/sample-deequ/src/test/scala/constraintSuggestion.scala:43)
  ... 50 elided

**Comment by jshao111** [comment]
Is there a workaround? I got the same issue

**Comment by mikenyaga** [comment]
I have spark 3.2.1 same error

Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.2.1
      /_/

Using Scala version 2.12.15, OpenJDK 64-Bit Server VM, 11.0.12
Branch HEAD
Compiled by user hgao on 2022-01-20T19:26:14Z
Revision 4f25b3f71238a00508a356591553f2dfa89f8290
Url https://github.com/apache/spark
Type --help for more information.




java.lang.AbstractMethodError: Missing implementation of resolved method 'abstract org.apache.spark.sql.catalyst.trees.TreeNode withNewChildrenInternal(scala.collection.IndexedSeq)' of abstract class org.apache.spark.sql.catalyst.trees.TreeNode.
  at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$withNewChildren$2(TreeNode.scala:359)
  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:82)
  at org.apache.spark.sql.catalyst.trees.TreeNode.withNewChildren(TreeNode.scala:358)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:595)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:486)
  at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$3(TreeNode.scala:486)
  at scala.collection.immutable.List.map(List.scala:293)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:595)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:486)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:457)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transform(TreeNode.scala:425)
  at org.apache.spark.sql.catalyst.util.package$.usePrettyExpression(package.scala:128)
  at org.apache.spark.sql.catalyst.util.package$.toPrettySQL(package.scala:158)
  at org.apache.spark.sql.RelationalGroupedDataset.alias(RelationalGroupedDataset.scala:89)
  at org.apache.spark.sql.RelationalGroupedDataset.$anonfun$toDF$1(RelationalGroupedDataset.scala:65)
  at scala.collection.immutable.List.map(List.scala:297)
  at org.apache.spark.sql.RelationalGroupedDataset.toDF(RelationalGroupedDataset.scala:65)
  at org.apache.spark.sql.RelationalGroupedDataset.agg(RelationalGroupedDataset.scala:255)
  at org.apache.spark.sql.Dataset.agg(Dataset.scala:1890)
  at com.amazon.deequ.analyzers.runners.AnalysisRunner$.liftedTree1$1(AnalysisRunner.scala:326)
  at com.amazon.deequ.analyzers.runners.AnalysisRunner$.runScanningAnalyzers(AnalysisRunner.scala:318)
  at com.amazon.deequ.analyzers.runners.AnalysisRunner$.doAnalysisRun(AnalysisRunner.scala:167)
  at com.amazon.deequ.VerificationSuite.doVerificationRun(VerificationSuite.scala:121)
  at com.amazon.deequ.VerificationRunBuilder.run(VerificationRunBuilder.scala:173)
  ... 60 elided

**Comment by sudsali** [comment]
Closing as a version compatibility issue. Deequ 2.0.0 did not support Spark 3.2. This was fixed in Deequ 2.0.1+ (PR #416). Use Deequ 2.0.1-spark-3.2 or later for Spark 3.2 compatibility.
